<?php

namespace fancycv;

DEFINE('FORMATTERS', __DIR__.'/../src/yml/fancycv/formatters/');
DEFINE('DATA_DIR', __DIR__.'/../data/');
// Autoloader generated by Composer (php composer.phar install --dev)
$loader = require __DIR__ . '/../vendor/autoload.php';

?>